//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegProject.Dto
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    [DataContract]
    [Serializable]
    public class DtoRoleAction
    {
    
    	[DataMember]
        public int Id { get; set; }
    	[DataMember]
        public int RoleId { get; set; }
    	[DataMember]
        public int ControllerId { get; set; }
    	[DataMember]
        public int ActionId { get; set; }
    	[DataMember]
        public int Status { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> CreateDate { get; set; }
    	[DataMember]
        public Nullable<int> CreatorId { get; set; }
    
    	[DataMember]
        public  DtoRoles Roles { get; set; }
    	[DataMember]
        public  DtoSystemActions SystemActions { get; set; }
    	[DataMember]
        public  DtoSystemControllers SystemControllers { get; set; }
    }
}
