//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegProject.Dto
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    [DataContract]
    [Serializable]
    public class DtoSystemControllers
    {
    
    	[DataMember]
        public int Id { get; set; }
    	[DataMember]
        public string Name { get; set; }
    	[DataMember]
        public Nullable<int> Status { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> CreateDate { get; set; }
    
    	[DataMember]
        public  ICollection<DtoRoleAction> RoleAction { get; set; }
    	[DataMember]
        public  ICollection<DtoSystemActions> SystemActions { get; set; }
    }
}
