//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegProject.Dto
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    [DataContract]
    [Serializable]
    public class DtoUserProfile
    {
    
    	[DataMember]
        public int Id { get; set; }
    	[DataMember]
        public int UserId { get; set; }
    	[DataMember]
        public string NameSurname { get; set; }
    	[DataMember]
        public string Adres { get; set; }
    	[DataMember]
        public string Phone { get; set; }
    	[DataMember]
        public string Url { get; set; }
    	[DataMember]
        public int Status { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> CreateDate { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> ModifyDate { get; set; }
    
    	[DataMember]
        public  DtoUsers Users { get; set; }
    }
}
